name: Website Deployment

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Verification
        uses: actions/checkout@v1

      - name: LFTP install
        run: sudo apt-get install -y lftp

      - name: Create LFTP script
        run: |
          cat > deploy.lftp << EOF
          open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} ${{ secrets.FTP_HOST }}
          
          # Global settings
          set mirror:use-pget-n 5
          set mirror:parallel-transfer-count 5
          
          # Individual files
          echo "Transferring individual files..."
          put index.php -o www/index.php
          put .htaccess -o www/.htaccess
          
          # Individual file in subdirectory
          mkdir -f -p www/style/
          put style/style.css -o www/style/style.css
          
          mkdir -f -p www/style/
          put script/script.js -o www/script/script.js
          echo "Transferred individual files successfully."
          
          # Recursive directories
          echo "Transferring directories..."
          mirror -R admin/ www/admin/
          mirror -R data/ www/data/
          mirror -R error/ www/error/
          mirror -R functions/ www/functions/
          mirror -R medias/ www/medias/
          mirror -R projects/ www/projects/
          
          echo "Transferred directories successfully."
          
          bye
          EOF

      - name: Deployment script execution
        run: |
          echo "Script beginning..."
          echo -e "\033[1;32mConnected to ${{ secrets.FTP_HOST }} with username ${{ secrets.FTP_USER }}\033[0m"
          lftp -f deploy.lftp
          echo "Script finished."
          