name: Website Deployment

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Verification
        uses: actions/checkout@v1

      - name: LFTP install
        run: sudo apt-get install -y lftp

      - name: Create LFTP script
        run: |
          cat > deploy.lftp << EOF
          open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} ${{ secrets.FTP_HOST }}
          
          # Global settings
          set mirror:use-pget-n 5
          set mirror:parallel-transfer-count 5
          
          # Individual files
          echo -e "\033[1;34mTransfering individual files...\033[0m"
          put index.php -o www/index.php
          put .htaccess -o www/.htaccess
          
          # Individual file in subdirectory
          mkdir -f -p www/style/
          put style/style.css -o www/style/style.css
          echo -e "\033[1;32mTransfered individual files successfully.\033[0m"
          
          # Recursive directories
          echo -e "\033[1;34mTransfering directories files...\033[0m"
          mirror -R admin/ www/admin/
          mirror -R data/ www/data/
          mirror -R error/ www/error/
          mirror -R functions/ www/functions/
          mirror -R medias/ www/medias/
          mirror -R projects/ www/projects/
          
          # Mirror specific directories
          mirror -R script/minified/ www/script/minified/
          echo -e "\033[1;32mTransfered individual files successfully.\033[0m"
          
          bye
          EOF

      - name: Deployment script execution
        run: |
          echo "Script beginning..."
          echo -e "\033[1;32mConnected to ${{ secrets.FTP_HOST }} with username ${{ secrets.FTP_USER }}\033[0m"
          lftp -f deploy.lftp
          echo "Script finished."
          